# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b515d8a94ef10b0ba9889c2ad115ec75d98bfac6b9d3027e0a0a61ed40c0c3f59458d83708c17b89f195dcbc6b01ac6c9bd8adbf5fe9c67644d42e3f64f0020

test:
  secret_key_base: e768863852096eddc26e702aa4d77af48da6784b3d673cf44cf908f8f7d663819ac50597bf20f7e11f2757c281fc550872619bcb26166e8f1e0ed229acdf30ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
